from tkinter import *
import webbrowser
from PIL import Image, ImageTk
def task_gui(extracted_links):
    print(extracted_links)
    root = Toplevel()
    root.geometry('2700x2700')
    # root.attributes('-fullscreen', True)
    image = Image.open("captcha1.png")
    image = image.resize((250, 160), Image.ANTIALIAS)
    photo = ImageTk.PhotoImage(image)
    image2 = Image.open("captcha2.png")
    image2 = image2.resize((250, 160), Image.ANTIALIAS)
    photo2 = ImageTk.PhotoImage(image2)
    image3 = Image.open("captcha3.png")
    image3 = image3.resize((250, 160), Image.ANTIALIAS)
    photo3 = ImageTk.PhotoImage(image3)
    image4 = Image.open("captcha4.png")
    image4 = image4.resize((250, 160), Image.ANTIALIAS)
    photo4 = ImageTk.PhotoImage(image4)
    b1 = Button(root, text=" "+extracted_links[0][1],command=lambda: webbrowser.open(extracted_links[0][0]))
    b2 = Button(root, text=" "+extracted_links[1][1],command=lambda: webbrowser.open(extracted_links[1][0]))
    b3 = Button(root, text=" "+extracted_links[2][1],command=lambda: webbrowser.open(extracted_links[2][0]))
    b4 = Button(root, text=" "+extracted_links[3][1],command=lambda: webbrowser.open(extracted_links[3][0]))
    label1 = Label(root, image=photo)
    label1.place(x=35, y=100)
    b1.place(x=300, y=100)
    label2 = Label(root, image=photo2)
    label2.place(x=35, y=300)
    b2.place(x=300, y=300)  
    label3 = Label(root, image=photo3)
    label3.place(x=35, y=500)
    b3.place(x=300, y=500)
    label4 = Label(root, image=photo4)
    label4.place(x=35, y=700)
    b4.place(x=300, y=700)

    root.mainloop()