#List
print("LIST WITH STRING")
colour = ["yellow","blue","purple","black"]
print(colour)
print("\n")
print("APPEND METHOD")
colour.append("red")
print(colour)
print("\n")
print("POP METHOD")
colour.pop(2)
print(colour)
print("\n")
print("REMOVE METHOD")
colour.remove("yellow")
print(colour)
print("\n")
print("SORT METHOD")
colour.sort()
print(colour)
print("\n")
print("-------------------------------------------------------------------------------")
print("\n")
print("LIST WITH INTEGERS")
num = [98,12,24,27,39]
print(num)
print("\n")
print("APPEND METHOD")
num.append(150)
print(num)
print("\n")
print("POP METHOD")
num.pop(2)
print(num)
print("\n")
print("REMOVE METHOD")
num.remove(39)
print(num)
print("\n")
print("SORT METHOD")
num.sort()
print(num)
